// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8rvQKTBRvO6bVNnjDrURUfznzoI7opKI',
    appId: '1:421871871759:web:771de011bc59bfc961807a',
    messagingSenderId: '421871871759',
    projectId: 'test2-c09a7',
    authDomain: 'test2-c09a7.firebaseapp.com',
    storageBucket: 'test2-c09a7.firebasestorage.app',
    measurementId: 'G-S28QDDYXDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFl5kAHJBkO24ehuHaSYQ4n1yHnBRZ8m4',
    appId: '1:421871871759:android:fb44eca500705f1761807a',
    messagingSenderId: '421871871759',
    projectId: 'test2-c09a7',
    storageBucket: 'test2-c09a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANfT8nEmfy8Uoa56lndBOS9-UUVSUWx7E',
    appId: '1:421871871759:ios:8dcc7ec68e3b348261807a',
    messagingSenderId: '421871871759',
    projectId: 'test2-c09a7',
    storageBucket: 'test2-c09a7.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
}
